# Generated by Django 4.1.1 on 2022-09-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_user_is_advisor_user_is_permitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_permitted',
        ),
        migrations.AddField(
            model_name='user',
            name='permitted_place',
            field=models.IntegerField(default=0),
        ),
    ]
