# Generated by Django 4.1.1 on 2022-09-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=10)),
                ('participants', models.JSONField()),
                ('classroom', models.TextField()),
                ('pub_date', models.TimeField()),
                ('period_1', models.BooleanField()),
                ('period_2', models.BooleanField()),
                ('is_permitted', models.BooleanField()),
                ('representative', models.IntegerField()),
                ('advisor', models.CharField(max_length=35)),
            ],
        ),
    ]
