# Generated by Django 4.1.1 on 2022-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission_1',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
