# Generated by Django 4.1.1 on 2022-09-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_alter_permission_1_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission_1',
            new_name='Permission',
        ),
    ]
