# Generated by Django 4.1.1 on 2022-09-11 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_rename_permission_1_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='classroom',
        ),
        migrations.AddField(
            model_name='permission',
            name='activity_detail',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='permission',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_permitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='period_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='period_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
